modLoader="javafml"
loaderVersion="[${fml},)"
license="MIT"

[[mods]]
modId="itemnamecopy"
version="${version}"
displayName="ItemNameCopy"
logoFile="assets/itemnamecopy/icon.png"
displayTest="IGNORE_ALL_VERSION"
description='''Copy a hovered item display name with Ctrl+C.'''

[features.itemnamecopy]
${java_feature}="[${java},)"

[[dependencies.itemnamecopy]]
modId="forge"
mandatory=true
versionRange="[${loader},)"
ordering="NONE"
side="CLIENT"

[[dependencies.itemnamecopy]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft}]"
ordering="NONE"
side="CLIENT"
