modLoader="javafml"
loaderVersion="[${fml},)"
license="MIT"

[[mods]]
modId="itemnamecopy"
version="${version}"
displayName="ItemNameCopy"
logoFile="assets/itemnamecopy/icon.png"
${display_test}
description='''Copy a hovered item display name with Ctrl+C.'''

[features.itemnamecopy]
javaVersion="[${java},)"

[[mixins]]
config="itemnamecopy.mixins.json"

[[dependencies.itemnamecopy]]
modId="neoforge"
${dependency_kind}
versionRange="[${loader},)"
ordering="NONE"
side="CLIENT"

[[dependencies.itemnamecopy]]
modId="minecraft"
${dependency_kind}
versionRange="[${minecraft}]"
ordering="NONE"
side="CLIENT"
