modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="itemnamecopy"
version="${version}"
displayName="ItemNameCopy"
description='''Copy a hovered item display name with Ctrl+C.'''

[[mixins]]
config="itemnamecopy.mixins.json"

[[dependencies.itemnamecopy]]
modId="neoforge"
type="required"
versionRange="[${loader},)"
ordering="NONE"
side="CLIENT"

[[dependencies.itemnamecopy]]
modId="minecraft"
type="required"
versionRange="[${minecraft}]"
ordering="NONE"
side="CLIENT"
