com.mojang.blaze3d.platform.ClipboardManager=net.minecraft.client.ClipboardHelper
net.minecraft.client.KeyboardHandler=net.minecraft.client.KeyboardListener
net.minecraft.client.gui.components.EditBox=net.minecraft.client.gui.widget.TextFieldWidget
net.minecraft.client.gui.components.events.ContainerEventHandler=net.minecraft.client.gui.INestedGuiEventHandler
net.minecraft.client.gui.components.events.GuiEventListener=net.minecraft.client.gui.IGuiEventListener
net.minecraft.client.gui.screens.Screen=net.minecraft.client.gui.screen.Screen
net.minecraft.client.gui.screens.inventory.AbstractContainerScreen=net.minecraft.client.gui.screen.inventory.ContainerScreen
net.minecraft.client.gui.screens.recipebook.RecipeBookComponent=net.minecraft.client.gui.recipebook.RecipeBookGui
net.minecraft.client.gui.screens.recipebook.RecipeUpdateListener=net.minecraft.client.gui.recipebook.IRecipeShownListener
net.minecraft.network.chat.Component=net.minecraft.util.text.ITextComponent
net.minecraft.network.chat.TranslatableComponent=net.minecraft.util.text.TranslationTextComponent
net.minecraft.world.inventory.Slot=net.minecraft.inventory.container.Slot
