children=getEventListeners
displayClientMessage=sendStatusMessage
getClipboard=getClipboardString
getHoverName=getDisplayName
getItem=getStack
getRecipeBookComponent=getRecipeGui
hasItem=getHasStack
keyboardHandler=keyboardListener
keyPress=onKeyEvent
screen=currentScreen
searchBox=searchBar
setClipboard=setClipboardString
